### ISSUE TITLE
yarn安装依赖报错

### ISSUE THREAD

**Issue by tanzhou2002** [BM-laoli/nestjs-http-server-template#1]
node 17.3.0
higth分支
执行 yarn 报错如下
error D:\workspace\learncode\Fontend\nest\source\node_modules\bcrypt: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: D:\workspace\learncode\Fontend\nest\source\node_modules\bcrypt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.8
node-pre-gyp info using node@17.3.0 | win32 | x64
node-pre-gyp info check checked for "D:\workspace\learncode\Fontend\nest\source\node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node" (not found)
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-win32-x64-unknown.tar.gz
node-pre-gyp ERR! install request to https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-win32-x64-unknown.tar.gz failed, reason: read ECONNRESET
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@5.0.1 and node@17.3.0 (node-v102 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error request to https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-win32-x64-unknown.tar.gz failed, reason: read ECONNRESET

D:\workspace\learncode\Fontend\nest\source\node_modules\bcrypt>if not defined npm_config_node_gyp (node "D:\Enviroment\node\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@17.3.0 | win32 | x64
gyp info ok

**Comment by BM-laoli** [comment]
注意: 本仓库将会迎来一次重大更新，这个问题将会一起修复
bcrypt 好像一直是个兼容性的问题，我试试你的17 版本
